Module3 task2
htmlacademy-php/1282861-yeticave-12 pull request #7
Opened 2020-12-07 13:49 UTC by sergey-komlev

2020-12-08 10:39 UTC, ademaro commented on index.php
> +date_default_timezone_set("Europe/Moscow");
это в конфиг

2020-12-08 10:46 UTC, ademaro commented on function.php
> +function end_time_lot($date) {
в многострочном комменте делай ещё одну строку и добавляй тип данных:
...плюс у тебя должен быть `@return` (ф-ция же возвращает значение)
```js
/** 
 * Функция для подсчета оставшегося времени
 * @param {string} $date — дата в формате ГГГГ-ММ-ДД
 * @return {int} — количество секунд
 */
```

2020-12-08 10:47 UTC, ademaro requested changes
Жду поправок

2020-12-15 10:59 UTC, ademaro commented on function.php
> +    return $secs_to_end;
```php
return "Осталось $hours часов $minutes минут";
return [
  hours => $hours,

]
```

2020-12-17 11:05 UTC, ademaro approved these changes

2020-12-17 11:05 UTC, merged

2021-01-08 10:51 UTC, sergey-komlev commented on index.php
> +date_default_timezone_set("Europe/Moscow");
+